name: wxReadExchange

on:
  schedule:
    - cron: '50 13 * * 0'  # 每周日北京时间21点50分执行
  workflow_dispatch:  # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'  # Specify the distribution

      - name: Build with Maven
        run: mvn clean install | tee build.log

      - name: Run WxReadHelp
        env:
          WX_READ_USERS: ${{ secrets.WX_READ_USERS }}
        run: java -cp target/wxReadHelp-0.1.jar cn.ustc.WxReadExchange